### ISSUE TITLE
메인 샘플에서 마우스를 올릴시 애니메이션 효과

### ISSUE THREAD

**Issue by hojae-lee** [ibsheet/loader-react-guide-samples#5]
샘플에 마우스를 올릴시 기본적으로 애니메이션 효과가 구현 되면 좋겟음... ibsheet.com 에 샘플정도

![image](https://user-images.githubusercontent.com/55069045/133923224-7f3c3afd-4441-41e1-899a-8fedc2395dd3.png)

**Comment by graydelay** [comment]
hover layer 가운데 버튼 추가 예정..
